#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d   3 4 5 6 7 8 9

bspc config border_width         5
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config top_padding 0
bspc config bottom_padding 0

bspc rule -a firefox desktop='^1'
bspc rule -a code-oss desktop='^2'








bspc config normal_border_color "#19252a"
bspc config active_border_color "#232f34"


bspc config focused_border_color "#ecd6ad"
bspc config presel_feedback_color "#2b5359"

bspc config focus_follows_pointer true
bspc config pointer_modifier    super


setxkbmap -option grp:alt_shift_toggle us,ru
#$HOME/.config/bin/picom --config $HOME/.config/picom/picom-pijulius.conf.back2                                     # Запуск picom
xsetroot -cursor_name left_ptr
xset s off
xset -dpms
#picom --config $HOME/.config/picom/picom-pijulius.conf.back2 &
sxhkd &
polybar &
picom &
nitrogen --restore &
