#!/bin/sh

sxhkd &

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config automatic_scheme alternate

bspc rule -a \* floating=off

feh --bg-scale ~/Pictures/wallpaper.jpg &
polybar example &
picom --config ~/.config/picom/picom.conf &

~/.config/bspwm/scripts/autostart.sh &
